In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('artists_datasets/language.csv')
df.head()

,track_id,track_name,artist_name,year,popularity,artwork_url,album_name,acousticness,danceability,duration_ms,...,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,track_url,language
0,2r0ROhr7pRN4MXDMT1fEmd,"Leo Das Entry (From ""Leo"")",Anirudh Ravichander,2024,59,https://i.scdn.co/image/ab67616d0000b273ce9c65...,"Leo Das Entry (From ""Leo"")",0.0241,0.753,97297.0,...,8.0,0.1000,-5.994,0.0,0.1030,110.997,4.0,0.459,https://open.spotify.com/track/2r0ROhr7pRN4MXD...,Tamil
1,4I38e6Dg52a2o2a8i5Q5PW,AAO KILLELLE,"Anirudh Ravichander, Pravin Mani, Vaishali Sri...",2024,47,https://i.scdn.co/image/ab67616d0000b273be1b03...,AAO KILLELLE,0.0851,0.780,207369.0,...,10.0,0.0951,-5.674,0.0,0.0952,164.995,3.0,0.821,https://open.spotify.com/track/4I38e6Dg52a2o2a...,Tamil
2,59NoiRhnom3lTeRFaBzOev,Mayakiriye Sirikiriye - Orchestral EDM,"Anirudh Ravichander, Anivee, Alvin Bruno",2024,35,https://i.scdn.co/image/ab67616d0000b27334a1dd...,Mayakiriye Sirikiriye (Orchestral EDM),0.0311,0.457,82551.0,...,2.0,0.0831,-8.937,0.0,0.1530,169.996,4.0,0.598,https://open.spotify.com/track/59NoiRhnom3lTeR...,Tamil
3,5uUqRQd385pvLxC8JX3tXn,Scene Ah Scene Ah - Experimental EDM Mix,"Anirudh Ravichander, Bharath Sankar, Kabilan, ...",2024,24,https://i.scdn.co/image/ab67616d0000b27332e623...,Scene Ah Scene Ah (Experimental EDM Mix),0.2270,0.718,115831.0,...,7.0,0.1240,-11.104,1.0,0.4450,169.996,4.0,0.362,https://open.spotify.com/track/5uUqRQd385pvLxC...,Tamil
4,1KaBRg2xgNeCljmyxBH1mo,Gundellonaa X I Am A Disco Dancer - Mashup,"Anirudh Ravichander, Benny Dayal, Leon James, ...",2024,22,https://i.scdn.co/image/ab67616d0000b2735a59b6...,Gundellonaa X I Am a Disco Dancer (Mashup),0.0153,0.689,129621.0,...,7.0,0.3450,-9.637,1.0,0.1580,128.961,4.0,0.593,https://open.spotify.com/track/1KaBRg2xgNeCljm...,Tamil

In [11]:
df.columns

Index(['track_id', 'track_name', 'artist_name', 'year', 'popularity',
       'artwork_url', 'album_name', 'acousticness', 'danceability',
       'duration_ms', 'energy', 'instrumentalness', 'key', 'liveness',
       'loudness', 'mode', 'speechiness', 'tempo', 'time_signature', 'valence',
       'track_url', 'language'],
      dtype='str')

In [10]:
df[df['artist_name'].apply(lambda x: 'Taylor' in x)]

,track_id,track_name,artist_name,year,popularity,artwork_url,album_name,acousticness,danceability,duration_ms,...,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,track_url,language
23511,1DJcbL8959LnaHt8nQc0PC,Better Than Revenge,Taylor Swift,2024,14,https://i.scdn.co/image/ab67616d0000b273cc4ff9...,Be My Anti-Valentine 2024,0.015500,0.517,220307.0,...,11.0,0.2630,-3.187,0.0,0.0912,145.871,4.0,0.5950,https://open.spotify.com/track/1DJcbL8959LnaHt...,English
23512,3ePJQGn7bgRKSULeswQsfw,We Are Never Ever Getting Back Together,Taylor Swift,2024,8,https://i.scdn.co/image/ab67616d0000b273cc4ff9...,Be My Anti-Valentine 2024,0.009880,0.535,193147.0,...,7.0,0.1090,-5.899,1.0,0.1700,172.028,4.0,0.7130,https://open.spotify.com/track/3ePJQGn7bgRKSUL...,English
23513,2GVxYaEiKIAvJzuFvxkhWd,Bad Blood,Taylor Swift,2024,7,https://i.scdn.co/image/ab67616d0000b273cc4ff9...,Be My Anti-Valentine 2024,0.089200,0.656,211933.0,...,7.0,0.2010,-6.104,1.0,0.1900,170.087,4.0,0.2950,https://open.spotify.com/track/2GVxYaEiKIAvJzu...,English
23514,1Iq8oo9XkmmvCQiGOfORiz,Is It Over Now? (Taylor's Version) (From The V...,Taylor Swift,2023,88,https://i.scdn.co/image/ab67616d0000b273904445...,1989 (Taylor's Version),0.050400,0.596,229478.0,...,0.0,0.1270,-7.346,1.0,0.0360,100.012,4.0,0.1760,https://open.spotify.com/track/1Iq8oo9XkmmvCQi...,English
23515,5KD6AEm19QnMbfWpfoOHMl,Now That We Don't Talk (Taylor's Version) (Fro...,Taylor Swift,2023,83,https://i.scdn.co/image/ab67616d0000b273904445...,1989 (Taylor's Version),0.186000,0.793,146437.0,...,0.0,0.0889,-9.319,1.0,0.0338,109.994,4.0,0.0662,https://open.spotify.com/track/5KD6AEm19QnMbfW...,English
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24520,6zpQwkOGOTt6OCnMdNKjHl,Shake It Off,Taylor Swift,2020,7,https://i.scdn.co/image/ab67616d0000b273cbd184...,Big Machine Dance Party,0.064700,0.647,219200.0,...,7.0,0.3340,-5.384,1.0,0.1650,160.078,4.0,0.9420,https://open.spotify.com/track/6zpQwkOGOTt6OCn...,English
24521,37enMB7tcsUq4CkibOC3Bx,Mean - Live,Taylor Swift,2020,3,https://i.scdn.co/image/ab67616d0000b2734b4b7c...,Big Machine Live!,0.152000,0.430,247373.0,...,4.0,0.3800,-4.377,1.0,0.0549,163.672,4.0,0.5650,https://open.spotify.com/track/37enMB7tcsUq4Ck...,English
24522,2zbVATcYiggJSWeSZkDFgd,Out Of The Woods,Taylor Swift,2020,3,https://i.scdn.co/image/ab67616d0000b273618f28...,Pride Month,0.000743,0.553,235800.0,...,7.0,0.3410,-6.937,1.0,0.0397,91.999,4.0,0.3390,https://open.spotify.com/track/2zbVATcYiggJSWe...,English
44162,7p6kSsTZWbLnNXxAcwSHD1,Now We Are Free (from the film Gladiator),"Hans Zimmer, Klaus Badelt, Lisa Gerrard, Becky...",2005,14,https://i.scdn.co/image/ab67616d0000b27327b009...,By Your Side,0.067200,0.396,290907.0,...,11.0,0.0983,-17.233,1.0,0.0333,136.980,4.0,0.0869,https://open.spotify.com/track/7p6kSsTZWbLnNXx...,English
56243,245uda182Ri7YysZ0gwXLL,I Need You Now,"Devan Ekambaram, Taylor Eigsti, Nel Bucktowar",2022,0,https://i.scdn.co/image/ab67616d0000b273cfe6ed...,Brindavan,0.230000,0.607,250467.0,...,2.0,0.3550,-5.767,0.0,0.0279,106.950,4.0,0.2810,https://open.spotify.com/track/245uda182Ri7Yys...,Tamil

In [12]:
df['language'].value_counts()

language
English      23392
Unknown      13005
Tamil        12681
Korean        6893
Hindi         5740
Telugu         324
Malayalam      282
Name: count, dtype: int64

In [14]:
df[df['language']=='Unknown']

,track_id,track_name,artist_name,year,popularity,artwork_url,album_name,acousticness,danceability,duration_ms,...,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,track_url,language
1254,50k2lO7Z6iP3VynsspdObS,Ori Vaari - Lofi Flip,"Santhosh Narayanan, Shree Mani, Abhishek Martyn",2024,8,https://i.scdn.co/image/ab67616d0000b2732de3a2...,Ori Vaari (Lofi Flip),0.79200,0.579,165553.0,...,2.0,0.4850,-11.638,1.0,0.0783,100.014,4.0,0.0913,https://open.spotify.com/track/50k2lO7Z6iP3Vyn...,Unknown
1255,12l4b9Bd6wwFueqhqUxUOq,"Neeye Oli - From ""Sarpatta Parambarai""","Santhosh Narayanan, Navz-47, SVDP",2024,18,https://i.scdn.co/image/ab67616d0000b2737c34da...,"Neeye Oli (From ""Sarpatta Parambarai"")",0.08940,0.592,237844.0,...,2.0,0.0400,-3.423,1.0,0.1810,160.051,4.0,0.3710,https://open.spotify.com/track/12l4b9Bd6wwFueq...,Unknown
1256,7Ci1TikgNInBn7KXyJo7a0,Wrong Pannadha,"Santhosh Narayanan, Gana Francis",2024,0,https://i.scdn.co/image/ab67616d0000b2738f0ae2...,Saindhav (Original Motion Picture Soundtrack),0.20900,0.884,217500.0,...,11.0,0.0852,-5.266,0.0,0.1590,128.055,4.0,0.5810,https://open.spotify.com/track/7Ci1TikgNInBn7K...,Unknown
1257,5DezAsjtSLUxW9j00eh0Ia,"Maamadura - From ""Jigarthanda DoubleX""","Santhosh Narayanan, Dhee, Vivek",2023,68,https://i.scdn.co/image/ab67616d0000b273f7d03c...,"Maamadura (From ""Jigarthanda DoubleX"")",0.11700,0.763,168750.0,...,9.0,0.0781,-7.504,1.0,0.2320,95.953,4.0,0.5490,https://open.spotify.com/track/5DezAsjtSLUxW9j...,Unknown
1258,7xnSWKXH8XVc8vML9132SZ,Unakku Thaan,"Santhosh Narayanan, Dhvani Kailas",2023,70,https://i.scdn.co/image/ab67616d0000b27368b8c8...,Chithha (Original Motion Picture Soundtrack),0.87500,0.578,216214.0,...,1.0,0.0973,-5.439,0.0,0.0304,139.640,3.0,0.5590,https://open.spotify.com/track/7xnSWKXH8XVc8vM...,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37253,0dqrmwx0IP64GTfzsqDoqE,"Aao Na (From ""Haider"")",Vishal Dadlani,2015,0,https://i.scdn.co/image/ab67616d0000b273f8ab96...,Haider & Other Hits,0.00995,0.526,255791.0,...,3.0,0.1210,-7.017,1.0,0.0404,135.954,4.0,0.5640,https://open.spotify.com/track/0dqrmwx0IP64GTf...,Unknown
37254,0DW9QbHNX4wxVxfQBuGWCS,Knock Out,Vishal Dadlani,2010,3,https://i.scdn.co/image/ab67616d0000b27309e066...,Knock Out,0.02690,0.713,252112.0,...,0.0,0.0723,-6.968,1.0,0.0581,107.001,4.0,0.7110,https://open.spotify.com/track/0DW9QbHNX4wxVxf...,Unknown
37255,6CJtkFpOyax0BzJ2GqNYME,"Lalla Lalla Lori (From ""Welcome 2 Karachi"")","Vishal Dadlani, Shivi",2017,1,https://i.scdn.co/image/ab67616d0000b273caba28...,Alco-Holiday - Weekend Special,0.09470,0.638,257050.0,...,8.0,0.1040,-3.255,0.0,0.0453,124.950,4.0,0.7290,https://open.spotify.com/track/6CJtkFpOyax0BzJ...,Unknown
37256,6wmztHc1PouTRZU0eroPo4,Sooraj Se Pehele Jagaane,Vishal Dadlani,2022,0,https://i.scdn.co/image/ab67616d0000b273c2313c...,Vijayanand - hi,0.11600,0.664,288667.0,...,4.0,0.2520,-10.005,0.0,0.0603,89.948,4.0,0.4970,https://open.spotify.com/track/6wmztHc1PouTRZU...,Unknown
37266,0Em0Q4edL2kcWrlhmkaOzR,"Besharam Rang (From ""Pathaan"")","Vishal and Sheykhar, Shilpa Rao, Caralisa Mont...",2024,1,https://i.scdn.co/image/ab67616d0000b27390ecbd...,Holi Party Mix,0.05870,0.773,258474.0,...,8.0,0.1540,-5.537,0.0,0.0412,115.997,4.0,0.6490,https://open.spotify.com/track/0Em0Q4edL2kcWrl...,Unknown

In [15]:
df[df['artist_name'].apply(lambda x: 'Aujla' in x)]

,track_id,track_name,artist_name,year,popularity,artwork_url,album_name,acousticness,danceability,duration_ms,...,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,track_url,language
47897,1WaqQIJ0iENGWZ1QmYvYNK,"Tauba Tauba (From ""Bad Newz"")",Karan Aujla,2024,71,https://i.scdn.co/image/ab67616d0000b2735960a3...,"Tauba Tauba (From ""Bad Newz"")",0.3290,0.676,207158.0,...,8.0,0.0998,-6.190,1.0,0.0503,95.102,4.0,0.842,https://open.spotify.com/track/1WaqQIJ0iENGWZ1...,Hindi
47898,3FqtduiaqnFYvBgKuc6QWQ,Winning Speech,"Karan Aujla, Mxrci",2024,77,https://i.scdn.co/image/ab67616d0000b2734a7287...,Winning Speech,0.1280,0.461,227442.0,...,11.0,0.1810,-5.004,0.0,0.3630,171.285,4.0,0.448,https://open.spotify.com/track/3FqtduiaqnFYvBg...,Hindi
47899,5ouREJYZCYqwF0p7VeUtfH,IDK HOW,Karan Aujla,2024,76,https://i.scdn.co/image/ab67616d0000b273f9d669...,Four Me,0.2190,0.464,175556.0,...,10.0,0.1460,-6.582,0.0,0.1830,83.918,1.0,0.213,https://open.spotify.com/track/5ouREJYZCYqwF0p...,Hindi
47900,7KmCQLSSde0UX5OqCgvGN9,ANTIDOTE,Karan Aujla,2024,74,https://i.scdn.co/image/ab67616d0000b273f9d669...,Four Me,0.0187,0.669,187333.0,...,8.0,0.0536,-5.581,0.0,0.1180,96.099,4.0,0.726,https://open.spotify.com/track/7KmCQLSSde0UX5O...,Hindi
47901,209QxKVJzh2FLUmZHpYs4m,God Damn,"Badshah, Karan Aujla, Hiten",2024,72,https://i.scdn.co/image/ab67616d0000b2739bb2d3...,Ek Tha Raja,0.0449,0.578,167234.0,...,1.0,0.1090,-6.247,1.0,0.1880,93.402,4.0,0.315,https://open.spotify.com/track/209QxKVJzh2FLUm...,Hindi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48199,4cU9Pl66UTn7w1Ba733SDZ,Yaar Graribaaz,"Dilpreet Dhillon, Karan Aujla, Shree Brar",2019,8,https://i.scdn.co/image/ab67616d0000b273e741eb...,Gedi Route - Punjabi Hits,0.2740,0.767,220023.0,...,4.0,0.1300,-2.000,0.0,0.0731,156.110,4.0,0.765,https://open.spotify.com/track/4cU9Pl66UTn7w1B...,Hindi
48200,5WFRB3x7ktiPb1UX08Sntw,Little Bit,"Jass Bajwa, Deep Jandu, Karan Aujla, Mahi Sand...",2019,11,https://i.scdn.co/image/ab67616d0000b27384854a...,Little Bit,0.0357,0.767,242305.0,...,1.0,0.3410,-4.800,0.0,0.0964,92.988,4.0,0.789,https://open.spotify.com/track/5WFRB3x7ktiPb1U...,Hindi
48201,5J8pMpCnFlFPh6v482Ejfk,Yaar Graribaaz,"Dilpreet Dhillon, Karan Aujla, Shree Brar",2019,6,https://i.scdn.co/image/ab67616d0000b273d7ede4...,Saga Top Hits,0.2740,0.767,220023.0,...,4.0,0.1300,-2.000,0.0,0.0731,156.110,4.0,0.765,https://open.spotify.com/track/5J8pMpCnFlFPh6v...,Hindi
48202,3PCXgwaCFmWRgSHxlrnSiQ,Tru Talk,"Jassie Gill, Karan Aujla",2019,0,https://i.scdn.co/image/ab67616d0000b273ac03bb...,The Very Best of Jassi Gill,0.2750,0.565,254087.0,...,8.0,0.1860,-1.833,0.0,0.3560,187.689,4.0,0.653,https://open.spotify.com/track/3PCXgwaCFmWRgSH...,Hindi
48203,4kTU1XirKE9UdvEi8S3VkZ,Don't Tell Me,"Dilpreet Dhillon, Karan Aujla, Gurlez Akhtar",2019,0,https://i.scdn.co/image/ab67616d0000b2738f94bb...,Sohnea 2 and Other Hits,0.1010,0.923,207735.0,...,1.0,0.2340,-3.994,1.0,0.0341,103.994,4.0,0.826,https://open.spotify.com/track/4kTU1XirKE9UdvE...,Hindi

In [25]:
df1 = pd.read_csv('songs_base_dataset.csv')
df1.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [26]:
df1['artists'] = df1['artists'].astype(str)

In [30]:
df1[df1['artists'].apply(lambda x: 'Taylor' in str(x))]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
725,725,6QYEoTGa0Boucy6htF83tb,Melvin Taylor;Lucky Peterson;Titus Williams;Ra...,"Plays the Blues for You (feat. Lucky Peterson,...",Cadillac Assembly Line,55,318333,False,0.735,0.355,...,-19.032,0,0.0387,0.65600,0.094000,0.1190,0.724,93.553,4,acoustic
774,774,3kYLpeRglpJLQkCsbp7p4j,Melvin Taylor;Lucky Peterson;Titus Williams;Ra...,"Plays the Blues for You (feat. Lucky Peterson,...",I 'll Play the Blues for You,52,317133,False,0.654,0.316,...,-18.692,0,0.0410,0.78600,0.056300,0.1310,0.697,94.485,4,acoustic
852,852,5MZYOtR8fcaZoWzweBNdMm,Brandon Chase;Taylor Manns,Dilemma,Dilemma,57,247683,False,0.627,0.246,...,-11.410,1,0.0342,0.78800,0.000000,0.1180,0.520,141.303,4,acoustic
1445,1445,3Wgg2Se9D2QL9I3oR8GUy8,Ebo Taylor,Love & Death,Mizin,22,312419,False,0.808,0.841,...,-5.990,1,0.0480,0.40200,0.000480,0.1850,0.891,106.477,4,afrobeat
1795,1795,6cLtKtakegCY6n7iepcLYJ,Ebo Taylor;Uhuru-Yenzu,Conflict,Love and Death,18,499733,False,0.804,0.920,...,-7.478,1,0.0563,0.15800,0.079700,0.0743,0.811,108.979,4,afrobeat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103606,103606,2e9GdZASfQ1PE5qgqdJxty,Teyana Taylor,Autumn Girl,Bare Wit Me,0,129806,True,0.714,0.495,...,-8.653,0,0.0817,0.14000,0.101000,0.2490,0.504,117.989,4,soul
107936,107936,1r6cqbmfVlAZYrrJMhBk7K,Synapson;Kaleem Taylor,Super 8,Filter Lover Pt. 2: Don't You (feat. Kaleem Ta...,23,221986,False,0.777,0.758,...,-5.016,0,0.2120,0.03990,0.000203,0.2250,0.836,118.076,4,synth-pop
109148,109148,7EkEG47RFRjxbpSafL0Ufp,York;Sin Plomo;Janet Taylor;JJ Flores,"Swanky Club House, Vol. 1",It's You - JJ Flores Remix Extended,0,382187,False,0.748,0.939,...,-5.230,1,0.0472,0.06070,0.310000,0.0891,0.398,126.984,4,techno
110249,110249,7EkEG47RFRjxbpSafL0Ufp,York;Sin Plomo;Janet Taylor;JJ Flores,"Swanky Club House, Vol. 1",It's You - JJ Flores Remix Extended,0,382187,False,0.748,0.939,...,-5.230,1,0.0472,0.06070,0.310000,0.0891,0.398,126.984,4,trance
110309,110309,10EpXLXKHmNSVKvX7A5hg8,Tritonal;Angel Taylor;Koven,Getaway (Remixes),Getaway - Koven Remix,61,203720,False,0.488,0.914,...,-2.875,0,0.2230,0.00415,0.000000,0.1580,0.222,172.187,4,trance